version: '2'
services:
    pudupi-app:
        image: pudupi
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://pudupi-mysql:3306/pudupi?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
            - SPRING_DATA_ELASTICSEARCH_CLUSTER_NODES=pudupi-elasticsearch:9300
        ports:
            - 8080:8080
    pudupi-mysql:
        extends:
            file: mysql.yml
            service: pudupi-mysql
    pudupi-elasticsearch:
        extends:
            file: elasticsearch.yml
            service: pudupi-elasticsearch
